### PR TITLE
PHP 7.3 release and removed MCrypt

### PR DESCRIPTION
**Pull request by esimonetti**

### CODE REVIEW

**Comment by ShadMickelberry** [comment]
Hello @esimonetti. Not questioning you but just a question on the removal of mcrypt from 7.3. I know of an old instance that will need some refectory if/when that is removed from the SOD platforms.

Thanks a lot

**Comment by esimonetti** [comment]
Hey @ShadMickelberry !

Thanks for reaching out. I was going with this post: https://community.sugarcrm.com/community/developer/blog/2019/01/07/preparing-for-php-73-support

It looks like php 7.2 removed mcrypt. With Sugar 9 if you need mcrypt you still have the option to use the php 7.1 stack I believe.

Hope it helps!

**Comment by ShadMickelberry** [comment]
@esimonetti 
Indeed and thank you very much for the reminder on the link. I'm really glad I did find this now and have some time to update. Really appreciate the work you put into this project. It has made a tremendous difference in my workflow.

**Comment by esimonetti** [comment]
@ShadMickelberry no problem!
I am really glad to hear that this project made a difference for you. Thanks for your positive feedback!

**Pull request merged**
