### PR TITLE
Support for sugarcrm 11

### PR DESCRIPTION
**Pull request by jsanchezL**
Hello guys, i share some changes for support Sugarcrm 11.0.

    * PHP - 7.4
    * Elasticsearch - 7.9

### CODE REVIEW

**Comment by ShadMickelberry** [comment]
@esimonetti @jsanchezL I think at least one issue with Elasticsearch is the allowed_contexts: search option in the config. I updated to score (I think) and it came up. 

I have also been testing and some options for XDebug 3 need updating (client_host and client_port) but I hadn’t gotten it fully working yet so I hadn’t commented yet.

**Comment by ShadMickelberry** [comment]
What I had tried in images/php/74/apache/config/php/mods-available/xdebug.ini was to set the Xdebug settings to the following. It is entirely likely the issue is entirely on my end but I can't get debugging to work on PHPStorm or VSCode after updating the settings in those environments. I'd be happy to test any suggestions.
`xdebug.idekey=XDEBUG_SESSION
xdebug.mode=debug
xdebug.client_host=10.10.10.1
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log`

**Comment by jsanchezL** [comment]
> @jsanchezL thanks for the contribution! I kindly asked two people test this contribution and they both could not get elastic 7.9 to work. Do you have to do anything special to get it to work?
> 
> cc @aserrazina @hectorrios

**Comment by jsanchezL** [comment]
oops, accidentally closed the pull, reopened the pull.

**Comment by jsanchezL** [comment]
@esimonetti Thinking about your observation, I already know what you mean. I did a couple of tests, now I have a change for the yml's, I will delete the ES directory, it no longer has a reason to be present.

**Comment by jjtbsomhorst** [comment]
when will it be merged?

**Review by esimonetti — APPROVED** [review]
Thank you for this contribution!

**Pull request merged**
